### ISSUE TITLE
Blocking call error

### ISSUE THREAD

**Issue by LoSk-p** [PinoutLTD/rrs-ha-integration#14]
```
Detected blocking call to scandir with args (22,) inside the event loop by custom integration 'robonomics_report_service' at custom_components/robonomics_report_service/utils.py, line 225: shutil.rmtree(dirpath) (offender: /usr/local/lib/python3.12/shutil.py, line 686: with os.scandir(topfd) as scandir_it:), please create a bug report at https://github.com/PinoutLTD/rrs-ha-integration/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#scandir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2751, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
  File "/config/custom_components/robonomics_report_service/report_service.py", line 43, in send_problem_report
    self._remove_tempdir(tempdir)
  File "/config/custom_components/robonomics_report_service/report_service.py", line 125, in _remove_tempdir
    delete_temp_dir(tempdir)
  File "/config/custom_components/robonomics_report_service/utils.py", line 225, in delete_temp_dir
    shutil.rmtree(dirpath)
```

**Comment by LoSk-p** [comment]
#16
